### ISSUE TITLE
Create schema and sample node list

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/node-list#1]
- [x] Create JSON or YAML schema file
- [x] Collect sample list of nodes
- [x] Enable travis to validate list against schema

**Comment by benhylau** [comment]
JSON is fine, but I would consider HTML form for submission to be a separate ticket for later. PR to add node means we don't need to set up any database. Just a text file that Travis can validate against schema before merge.

**Comment by dcwalk** [comment]
sure, PRs and a [PR template](https://github.com/blog/2111-issue-and-pull-request-templates) could work in the interim

**Comment by dcwalk** [comment]
Integrate with @Pedro-on-a-bike 's:  https://github.com/Pedro-on-a-bike/TOMeshNodeMap/blob/master/nodeListSchema.json

**Comment by dcwalk** [comment]
#2 attempts to address the YAML/JSON schema

**Comment by dcwalk** [comment]
Talking at the library today with @garrying, @darkdrgn2k @Shrinks99, we've hashed out Stage 1 for schema (to be added in #2):

- name
- longitude
- latitude
- IPv6
- cardinalDirection
- status (proposed | active) [option]

and thinking about stage 2:

- description (hardware stack, software stack, community)
- thinking about connecting to dynamic info needed for monitoring

**Comment by garrying** [comment]
I think this can be closed now?

**Comment by darkdrgn2k** [comment]
I think we completed and exhausted this ticket
Future evolution of this can be found in ticket #5
