### ISSUE TITLE
Free Geek Node - Information Sheet/Screen

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/node-list#19]
With the new Free Geek node up and running, Free Geek has asked us to prepare a page informing  the public of what exactly the node is.  They will put it next to the node. This sounds like a great opportunity to get exposed by the public.

Additional we have the option of using one of their may screens to show some information on it during the day.

Thoughts?

**Comment by dcwalk** [comment]
This sounds great! My only thought is this might not be the best repo to track this task? 

For all its faults the wekan might be, could consider flipping over to github issues & waffle.io to track across repos

**Comment by benhylau** [comment]
I have been using `mesh-isp` and `documents` to track some of these "cross-repo" tasks. Even if we put this into wekan, we still need a place for discussion, and GitHub Issues seem to be a reasonable choice that no one complained about so far as a place for discussion. Suggestions:

1. Use `mesh-isp` repo for deployment related tasks
2. Rename `mesh-isp` to `deployment` and use that

Thoughts?

**Comment by darkdrgn2k** [comment]
I would like to point out this is NOT linked to the antenna deployment we are trying to do at free geek but the actual node currently sitting on primes that we have been permitted to run.  This is more of a "publicity" stunt then anything.

I made this task because it was a request from Free Geek and i did not want it to be forgotten. If you wish to move it to a different repo that is total fine.

**Comment by benhylau** [comment]
Moved to https://github.com/tomeshnet/mesh-isp/issues/5
