### ISSUE TITLE
Define Schema for integration with monitoring (Stage 2)

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/node-list#5]
From #1, Stage 2 discussion with @garrying, @darkdrgn2k @Shrinks99 identified:

> - description (hardware stack, software stack, community)
> - thinking about connecting to dynamic info needed for monitoring

and going to copy in @Pedro-on-a-bike 's proposal for quick reference:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Toronto Mesh Nodes",
    "type": "array",
    "nodes": {
        "title": "Node Detail",
        "type": "object",
        "properties": {
            "name": {
                "type": "string"
            },
            "latitude": {
                "type": "number"
            },
            "longitude": {
                "type": "number"
            },
            "onlineStatus": {
                "type": "string",
                "enum": ["Online", "Offline"]
            },
            "cardinalDirection": {
                "type": "string",
                "enum": ["North", "North East", "East", "South East", "South", "South West", "West", "North West", "Omni"]
            },
            "floor": {
                "type": "integer"
            },
            "meshHardware": {
                "type": "string",
                "enum": ["Low Power Omni", "High Power Directional", "No H/W, Potential Location"]
            },
            "IPV6Address": {
                "type": "string"
            },
            "contact": {
                "type": "string"
            },
            "dateAdded": {
                 "type": "date-time"
            },
        "required": ["name", "nodeLocation", "online", "cardinalDirection", "floor", "meshHardware", "IPV6Address"]
        }
    }
}
```

**Comment by dcwalk** [comment]
Other thoughts:

- Do we want floor versus elevation?
- Is building type (e.g. condo? house?) important
- Want to understand how to prune old entries over time (date added helpful for that)

**Comment by darkdrgn2k** [comment]
Current prototypes for monitoring include cjdns connected servers that generate supplementary json files.

changing the schema may not be required as the supplementary files will provide required information.

**Comment by benhylau** [comment]
Real-time information from monitoring should not be included in schema. As long as we have a unique key that identifies a node that monitoring knows about (i.e. IPv4) we can associate data in our real-time systems and render.

@YurkoWasHere @Pedro-on-a-bike if you guys think we need to add these to schema, we can add new keys to schema-v7 or v8:

>- Do we want floor versus elevation?
>- Is building type (e.g. condo? house?) important

If not please go ahead and close this issue.

**Comment by darkdrgn2k** [comment]
> Real-time information from monitoring should not be included in schema. As long as we have a unique key that identifies a node that monitoring knows about (i.e. IPv4) we can associate data in our real-time systems and render.

Agreed! Real time data should be pulled from a dynamic source, not from a static source.

> Floor vs Elevation

I would suggest stick with Elevation, we can do a rough math for floor to elevation but NOTHING else out there cares about floor.

Also "roof" is not a floor so that breaks.

**Comment by benhylau** [comment]
Sounds like we can close this.
