### ISSUE TITLE
Switch to json object vs. array in node list

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/node-list#8]
Copying over @garrying & @darkdrgn2k 's comment from #6:
> Should this be an object instead of an array? Referencing the schema

@darkdrgn2k
> The code i got from Pedro seems to reference it as an array, so the site is coded to look for an array. I would have to go back and change the code to treat it as an object. I ran the Schema and the Node List via http://www.jsonschemavalidator.net/ and it checks out. In fact Javascript and above site errors out parsing { instrad of [

@garrying 
> We'd need to add keys to the node objects for to it validate. I'd be okay with keeping it as is for now.

**Comment by benhylau** [comment]
This is resolved now. Current schema validates.
